### PR TITLE
Feature/main

### PR DESCRIPTION
**Pull request by clitetailor**
This merge request contains the main features of React Epic.

 Todo in the Future:
- [ ] Add tests
- [ ] Support `withRxAdvanced`
- [ ] Add CI/CD
- [ ] Add support for History API (Considering whether to invite @imcvampire or not). For example
```jsx
import { createBrowserHistory } from 'history'

const history = createBrowserHistory()

<Provider runEpics={[
    browserHistoryEpic(history)
]} />
```
- [ ] Considering whether to add support for SSR (React Epic should works fine with SSR instead)

### CODE REVIEW

**Comment by imcvampire** [comment]
Lgtm!

**Comment by clitetailor** [comment]
@imcvampire Can you help me with the above changes? :3

**Comment by clitetailor** [comment]
I finally got it, the lib icon! :3
reactepic

**Comment by clitetailor** [comment]
Fun Fact: We don't even need to re-implement all the source code in Typescript. Just convert the file extension to .ts

Compiler: Consider using Rollup, FuseBox or Parcel
Context API: Provide a compat version of Context API Legacy
Decorator: Consider using New or Legacy API of Decorator

**Comment by clitetailor** [comment]
Meet a Big Wall. a very big fence of the Component internal state and HOC. May need a re-implementation of all the source code!?

**Comment by clitetailor** [comment]
Big game changer, consider rename `WithRx` to `WithStore` or `Connect` and re-implement another version of `WithRx`!

**Comment by clitetailor** [comment]
Decision: Keeping the previous implementation of `WithRx`. The new implementation is two expensive and not worth to provide a HOC with it

**Comment by clitetailor** [comment]
Cascading update problem may be solved, need to be investigated!

**Comment by clitetailor** [comment]
Yeah, the cascading warning come back to use again. Nice to see you "Cascading warning" 😄

**Comment by clitetailor** [comment]
The roadmap has moved to here:
https://github.com/clitetailor/react-epic/issues/2

**Comment by clitetailor** [comment]
Considering remove the implementation of `sync` and `syncReplay` in flavor of `shareReplay`

**Comment by clitetailor** [comment]
I already archive a big new step in **Execution Context in RxJS** technique. **Execution Context** maybe one of the greatest technique underlying RxJS. Document about Execution Context will be updated soon!

**Comment by clitetailor** [comment]
Seems like this library is strong for app logic only, not strong for UI building. We may need some other third party libraries or tools too strengthen this!

**Pull request merged**
